backend:
  name: github
  repo: your-username/your-repo-name # Replace with your GitHub username/repo
  branch: main # or master

media_folder: "assets/images" # Where uploaded images will be saved in your repo
public_folder: "assets/images"

collections:
  - name: "events"
    label: "Events"
    folder: "data/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
